### ISSUE TITLE
How to define enum without name?

### ISSUE THREAD

**Issue by mnbv09870987** [PerlFFI/FFI-Platypus-Type-Enum#5]
I am doing perl binding for SDL2 https://www.libsdl.org/download-2.0.php

in `include / SDL_pixels.h` there is the following unnamed enum:
```
enum
{
    SDL_BITMAPORDER_NONE,
    SDL_BITMAPORDER_4321,
    SDL_BITMAPORDER_1234
};
```

Please document how to define this enum?
```
	$ffi->load_custom_type('::Enum', '?????? which name I should use here?',
		{ ret => 'int', package => 'SDL2::Pixels' },
		'SDL_BITMAPORDER_NONE',
		'SDL_BITMAPORDER_4321',
		'SDL_BITMAPORDER_1234',
	);
```

**Comment by plicease** [comment]
This name is what is used by Platypus in function definitions.  It's not clear to me from the `.h` file which functions use these constants, but if you had a function:

```c
void foo(int bitmaporder);
...
foo(SDL_BITMAPORDER_NONE);
```

Then from Perl:

```perl
$ffi->load_custom_type('::Enum', 'mybitmaporder_t',
  { ret => 'int', package => 'SDL2::Pixels', type => 'int' },
  'SDL_BITMAPORDER_NONE',
  'SDL_BITMAPORDER_4321',
  'SDL_BITMAPORDER_1234',
);
$ffi->atttach_function( foo => [ 'mybitmaporder_t' ] );
foo(SDL_BITMAPORDER_NONE);
```

You want to make sure you specify the `type` when the enum types are used just to generate constants, and not used as argument types because on some architectures the `enum` or `senum` type might not match the actual type.

You may also want to consider `use constant` as an alternative here though you don't get checking on bogus values.

**Comment by mnbv09870987** [comment]
Ok, thank you. But it is still not clear for me which `$name` I should use for unnamed `enum`:
```
enum
{
    SDL_BITMAPORDER_NONE,
    SDL_BITMAPORDER_4321,
    SDL_BITMAPORDER_1234
};
```

It will be good if PTE will generate some random value when `undef` is provided as name.

So I suggest next syntax for unnamed `enum`:

```
$ffi->load_custom_type('::Enum', undef,
     ...
```

Does this suggestion seem reasonable to you?

**Comment by plicease** [comment]
> 
> 
> Ok, thank you. But it is still not clear for me which `$name` I should use for unnamed `enum`:
> 
> ```
> enum
> {
>     SDL_BITMAPORDER_NONE,
>     SDL_BITMAPORDER_4321,
>     SDL_BITMAPORDER_1234
> };
> ```
> 
> It will be good if PTE will generate some random value when `undef` is provided as name.
> 
> So I suggest next syntax for unnamed `enum`:
> 
> ```
> $ffi->load_custom_type('::Enum', undef,
>      ...
> ```
> 
> Does this suggestion seem reasonable to you?

No... not really.  Custom types are for passing values into functions.  Without a name there is no way to define a function that will take the type.  Custom types aren't really there to define constants.  This type plugin happens to creates them as a convenience because it makes sense for enum types.  If you just want constants then you can and should use the `constant` pragma instead.

**Comment by mnbv09870987** [comment]
so, if I understand correct. you recommend to use:
```
use constant   SDL_BITMAPORDER_NONE => 0;
use constant   SDL_BITMAPORDER_4321  => 1;
use constant   SDL_BITMAPORDER_1234 => 2;

```

**Comment by plicease** [comment]
Yes, either with `constant` or if you are okay with bundling C code you can use `FFI::Platypus::Constant`

https://metacpan.org/pod/FFI::Platypus::Type#Enum-types
