### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by KES777** [PerlFFI/FFI-Platypus-Type-Enum#8]
https://metacpan.org/pod/release/PLICEASE/FFI-Platypus-Type-Enum-0.03/lib/FFI/Platypus/Type/Enum.pm#prefix

![image](https://user-images.githubusercontent.com/799021/94363051-2a6a4980-00c8-11eb-83b9-6de3a37a1752.png)

From examples it should be `ret`

Also a bit [upper](https://metacpan.org/pod/release/PLICEASE/FFI-Platypus-Type-Enum-0.03/lib/FFI/Platypus/Type/Enum.pm#maps)

I do not understand what is maps. And what would occur if I provide not empty array reference.
And if array is not empty, which values it should have?

**Comment by KES777** [comment]
Should it be `foo_enum` instead of `foo_t`?

![image](https://user-images.githubusercontent.com/799021/94363174-1b37cb80-00c9-11eb-9e4a-df2c536bcfce.png)

**Comment by plicease** [comment]
> From examples it should be `ret`

Ah thanks.  I remember seeing this the other day and should have opened a ticket to remind myself, but forgot.  It is actually `rev`, the synopsis is wrong, but reviewing the code I can see that I chose to call this `rev` though `ret` might have been more appropriate.

#10 updates the documentation appropriately

> Also a bit [upper](https://metacpan.org/pod/release/PLICEASE/FFI-Platypus-Type-Enum-0.03/lib/FFI/Platypus/Type/Enum.pm#maps)
> 
> I do not understand what is maps. And what would occur if I provide not empty array reference.
> And if array is not empty, which values it should have?

Maps provides the internal mapping to the caller and the type.  It's used by `FFI::C` for some introspection, and included in the documentation for completeness but normally you do not need to use this.

> Should it be foo_enum instead of foo_t?

This is a bit confusing, but no.  The intent here is to use the constants from an enum, but you actually pass in a different integer types for which you know the size/sign.  This is useful when calling from a language other than C because the size and sign of an `enum` is not defined by the C standard.  I've seen this pattern in Rust C APIs, and it makes sense when you can control the header file.  Platypus needs to work with interfaces that are potentially not as FFI friendly so it probes for the usual size of enums.

I've added some comments to the example code that hopefully makes it a bit clearer in #10

**Comment by plicease** [comment]
I think this should be addressed with version `0.04`, but please let me know if you see any other typos or things that are unclear.

**Comment by KES777** [comment]
Thank you for fast fix. If I found some typos I will report.

The unclear things is when struct has another struct. I see that there are some variants: object, opaque pointer or via record package. But I can not find working example. All are one level deep (or I just do not understand), But I need struct, which could have another struct. And last one also could have another struct...

Like [here](https://github.com/PerlFFI/FFI-Platypus/issues/273)
